### ISSUE TITLE
Hotspot labels aren't positioning correctly relative to hotspots

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/adventure-materia-widget#15]
They consistently default to the top-left corner of the image.

**Comment by iturgeon** [comment]
![2019-03-01 10 40 24](https://user-images.githubusercontent.com/73480/53648669-7c0dd200-3c0e-11e9-9e4e-f47d4bfbb26b.gif)

**Comment by clpetersonucf** [comment]
This was resolved in the v2.1 release: https://github.com/ucfopen/adventure-materia-widget/releases/tag/v2.1.0 but the issue was never closed. Closing.
