### ISSUE TITLE
Suggestion: Add ability to embed YouTube or other video

### ISSUE THREAD

**Issue by mrash2** [ucfopen/adventure-materia-widget#43]
Suggestion for your consideration: Any chance we could add the ability to embed media in, say, a Narrative node? Or perhaps add a new node type for YouTube, Vimeo, etc.? I know we wouldn't want to accept video files directly within Materia, but it would be nice to be able to embed streamed video.

**Comment by clpetersonucf** [comment]
Talk about serendipitous timing, because we're actually working on this right now! It's been a much-requested feature for a while and we're thrilled to finally be adding support for embedding external video. No ETA on when the update will arrive, but it's currently actively being worked on.

**Comment by clpetersonucf** [comment]
Video support is now included in Adventure 2.3.0! 🎉

**Comment by mrash2** [comment]
Fantastic news! Thank you so much!

Sent from my iPhone. Please forgive typos or erroneous autocorrects.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
